# 
# main
#   generated by nullptr on 2025/10/10
# 

from kivy.app import App
from kivy.uix.screenmanager import ScreenManager

from Assets.Screens.Home.HomeScreen import HomeScreen
from Assets.Screens.ApiTest.ApiTestScreen import ApiTestScreen
from Assets.Screens.VoiceTest.VoiceTestScreen import VoiceTestScreen

class ControlScreenManager(ScreenManager):
    """Screen management class"""
    pass

class GianApp(App):
    """The core of the app class"""
    
    title = 'GIAN'
    icon  = './images/logo.png'

    def build(self):
        """App build"""
        screenManager = ControlScreenManager()
        screenManager.add_widget(HomeScreen(name = 'home'))
        screenManager.add_widget(ApiTestScreen(name = 'apiTest'))
        screenManager.add_widget(VoiceTestScreen(name = 'voiceTest'))
        return screenManager

if __name__ == '__main__':
    GianApp().run()