# 
# main
#   generated by nullptr on 2025/10/10
# 

from kivy.app import App
from kivy.core.text import LabelBase
from kivy.resources import resource_add_path
from kivy.uix.screenmanager import ScreenManager

from Assets.Screens.Home.HomeScreen import HomeScreen
from Assets.Screens.ApiTest.ApiTestScreen import ApiTestScreen
from Assets.Screens.VoiceTest.VoiceTestScreen import VoiceTestScreen


resource_add_path("Assets/Common/Font")
LabelBase.register(
    name="DotGothic16",
    fn_regular="Assets/Common/Font/DotGothic16-Regular.ttf",
)

class ControlScreenManager(ScreenManager):
    """Screen management class"""
    pass

class GianApp(App):
    """The core of the app class"""

    title = 'GIAN'
    icon  = 'Assets/Common/Images/logo.png'
    font_name = "DotGothic16"

    def build(self):
        """App build"""
        screenManager = ControlScreenManager()
        screenManager.add_widget(HomeScreen(name = 'home'))
        screenManager.add_widget(ApiTestScreen(name = 'apiTest'))
        screenManager.add_widget(VoiceTestScreen(name = 'voiceTest'))
        return screenManager

if __name__ == '__main__':
    GianApp().run()