#
# main
#   generated by nullptr on 2025/10/10
#

from kivy.app import App
from kivy.uix.screenmanager import ScreenManager

from Assets.Screens.Home.HomeScreen import HomeScreen
from Assets.Screens.ApiTest.ApiTestScreen import ApiTestScreen
from Assets.Screens.VoiceTest.VoiceTestScreen import VoiceTestScreen


class ControlScreenManager(ScreenManager):
    """Screen management class"""
    pass


class GianApp(App):
    """The core of the app class"""

    title = 'GIAN'
    icon = 'Assets/Common/Images/logo.png'

    def build(self):
        """App build"""
        screen_manager = ControlScreenManager()
        screen_manager.add_widget(HomeScreen(name='home'))
        screen_manager.add_widget(ApiTestScreen(name='apiTest'))
        screen_manager.add_widget(VoiceTestScreen(name='voiceTest'))
        return screen_manager


if __name__ == '__main__':
    GianApp().run()
