#
# main
#   generated by nullptr on 2025/10/10
#

from kivy.uix.screenmanager import Screen
from kivy.lang import Builder

Builder.load_file('Assets/Screens/Home/HomeScreen.kv')


class HomeScreen(Screen):
    """Home screen class"""

    def on_enter(self):
        """Just before the screen appears"""
        print("Home Screen Entered!")
